import { Operators } from "@/components/Table/tableTools";

export const ecnInstrumentSearchableColumns = [
  'name',
  'descr',
  ['marginMode', 'name'],
  'basis',
  'commission',
  'commissionAgent',
  ['commissionAgentLotsMode', 'name'],
  ['commissionAgentType', 'name'],
  ['commissionLotsMode', 'name'],
  ['commissionType', 'name'],
  'contractSize',
  'currency',
  'expirationDatetime',
  ['instrumentGroup', 'name'],
  'instrumentHash',
  'marginCurrency',
  'marginDivider',
  'marginHedged',
  'marginInitial',
  'marginMaintenance',
  'maxQuoteDeviation',
  'maxQuoteTimeDeviation',
  'priceDigits',
  'priceLiquidityLimit',
  ['profitMode', 'name'],
  'startExpirationDatetime',
  'swapEnable',
  'swapLimit',
  'swapLong',
  ['swapRollover3Days', 'name'],
  'swapShort',
  ['swapType', 'name'],
  'tickPrice',
  'tickSize',
  'tsPriceLiquidityLimit',
].map(field => ({
  field,
  operator: Operators.containsLow,
}));
