import { Operators } from "../../Table/tableTools";

export const usersInstSearchableColumns = [
  'name',
  ['action', 'name'],
  'userComment',
  'leverage',
  'balance',
  'credit',
  'margin',
  'freeMargin',
  'marginLevel',
  'marginWithLimits',
  'profitloss',
  'swap',
  'stopoutHash',
  'stopoutName',
  'stopoutSuppressTime',
  'stopoutGenerationTime',
  ['module', 'name'],
  ['marginModule', 'name'],
  'commission',
  'commissionValue',
  ['commissionType', 'name'],
  ['commissionLotsMode', 'name'],
  'commissionTurnover',
  'rolloverTime',
  ['company', 'name'],
  'trId',
  'hedgeFactor',
  'ts',
  'tsMs',
].map(field => ({
  field,
  operator: Operators.containsLow,
}));
